### ISSUE TITLE
pages.ubuntu.com search field obscured by an orange rectangle

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/www.ubuntu.com#4398]
1. Go to any pages.ubuntu.com page.
2. If necessary, resize the viewport to be at least 1030 pixels wide.
3. Look at the search field.

What you see: A lighter orange rectangle obscuring the search field.
![pages ubuntu com-search](https://user-images.githubusercontent.com/19801137/48612411-dac17f80-e980-11e8-886a-cba48a554ede.png)

What you should see: No such rectangle.

The rectangle disappears when hovering over the field.

---
*Reported from: https://pages.ubuntu.com/Low_Latency_Report.html*

**Comment by anasereijo** [comment]
@matthewpaulthomas looks okay to me. can you please check if it's still happening to you? thank you

**Comment by matthewpaulthomas** [comment]
Sorry I missed this earlier. It didn’t happen for me on visiting the page again, but on reloading, it happens consistently:

![www ubuntu com#4398-rectangle](https://user-images.githubusercontent.com/19801137/54761611-51e67900-4bea-11e9-9e1e-e3005c211ef4.png)

This is in Firefox 65 on Ubuntu.

**Comment by anthonydillon** [comment]
@anasereijo could we add this as a small task please.

**Comment by anasereijo** [comment]
done. please estimate

**Comment by anasereijo** [comment]
please estimate

**Comment by matthewpaulthomas** [comment]
The culprit seems to be this CSS rule:
```css
form button[type="submit"], form input[type="submit"] {
	background: none repeat scroll 0 0 #dd4814;
	webkit-border-radius: 3px;
	-moz-border-radius: 3px;
	border-radius: 3px;
	box-sizing: border-box;
	color: #fff;
	display: inline-block;
	font-family: Ubuntu,Arial,"libra sans",sans-serif;
	font-size: 1.14286em;
	font-weight: 300;
	margin: 0;
	border: 0;
	cursor: pointer;
	padding: 8px 14px;
	text-align: center;
	text-decoration: none;
	width: 93%;
}
```

If I remove or disable that rule, the search button moves to the right middle of the field and its background becomes transparent:

![www ubuntu com#4398-search-button-fixed](https://user-images.githubusercontent.com/19801137/56090466-4826fd00-5e9a-11e9-816d-7148043e629f.png)

That’s still too far away from the right end of the field, but at least it looks plausible.
