### ISSUE TITLE
"sectors" heading in footer displyed incorrectly at small screen

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/www.ubuntu.com#4904]
## Summary

The "sectors" heading in the footer, at small screen isn't displayed correctly

## Current and expected result

Current result: see screenshot (below)

Expected result: the "sectors" heading should look the same as, for example, the "Downloads" one

## Screenshot

[if relevant, include a screenshot]
![image](https://user-images.githubusercontent.com/118614/55242635-8df68b00-5235-11e9-9492-4c512e32580a.png)

**Comment by matthewpaulthomas** [comment]
In the footer sitemap, top-level links are indented:
```css
.p-footer__title a:link, .p-footer__title a:visited {
    color: #666;
    padding-left: .25rem;
}
```

However, of the 54 items in the footer sitemap, “Sectors” is the only one that is not a link.

So probably this should be changed to something like:
```css
.p-footer__title li {
    padding-left: .25rem;
}
.p-footer__title a:link, .p-footer__title a:visited {
    color: #666;
}
```

(“Security”, “Public cloud” etc are also indented under “Sectors” as if they are children when they aren’t, but I think that’s a separate problem.)
